name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Unit
        run: |
          deno test --allow-all tests/unit

      # - name: Integration
      #   run: |
      #     deno test --allow-all --unsafely-ignore-certificate-errors tests/integration

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Formatter
        run: deno fmt --check

      - name: Linter
        run: deno lint

