name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Unit
        run: |
          deno test --allow-all tests/unit/tests.ts

      - name: Integration
        run: |
          deno test --allow-all tests/integration/app_3000/tests.ts
          #deno test --allow-all tests/integration/app_3001/tests.ts # throws rust errors

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check

      - name: Linter
        run: deno lint --unstable --ignore=tests/example_apps

